# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(default=0)),
                ('class_name', models.CharField(max_length=128)),
                ('module_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('changed_by', models.CharField(max_length=32, null=True)),
                ('changed_date', models.DateTimeField(null=True)),
                ('is_active', models.NullBooleanField()),
            ],
        ),
    ]
